### ISSUE TITLE
Always uses the first block selector

### ISSUE THREAD

**Issue by chuckhendo** [bancek/vscode-bem-expand#1]
Very cool idea, however, having a few issues with it. It seems to only work correctly the first time. After that, it always uses the first block.

Example: 
```html
<div class="test1">
  <div class="test1__child"></div>
</div>

<div class="test2">
  .&__child
</div>
```

If I press tab on the emmet selector there, it will autocomplete to `<div class="test1__child"></div>` instead of the expected `<div class="test2__child"></div>`

**Comment by bancek** [comment]
The current version of parser is very dumb. It uses first occurrence of `class=`. Otherwise it would have to parse HTML and JSX.

A simple way to solve this without complex parsing would be to use the last occurrence of `class=` that doesn't contain `__`.

Pull request is always welcome :)

**Comment by bancek** [comment]
This should be fixed by https://github.com/bancek/vscode-bem-expand/pull/5
