### ISSUE TITLE
Extension causes editor tab completion to fail

### ISSUE THREAD

**Issue by c4wrd** [bancek/vscode-bem-expand#2]
For some reason this extension is causing tab completion to fail on all documents. This extension works greatly and much better than the built in BEM expand in VSCode, so disabling this extension isn't much of an option. I'll take a look at this and submit a pull request with the fix.

**Comment by ihinckle** [comment]
Any luck with that? I'm having the same issue and finally found out the problem was this extension.

**Comment by ihinckle** [comment]
I looked into it myself and found a fix by editing the `when`.

`"when": "config.emmet.triggerExpansionOnTab && editorTextFocus && !editorHasMultipleSelections && !editorHasSelection && !editorReadonly && !editorTabMovesFocus && !suggestWidgetVisible"`

I have added a flag against the suggestion widget. This will ensure that snippets are not disabled when this plugin is active. I would like to submit a pull request but the repo is locked.

**Comment by bancek** [comment]
It should be possible to create a fork and then create a pull request.

**Comment by ihinckle** [comment]
Oh thanks. Learn something new about github all the time. I'll get that ready asap.

**Comment by ihinckle** [comment]
#3

**Comment by bancek** [comment]
Version `0.1.2` has just been released. It should appear in the Marketplace shortly.
