### ISSUE TITLE
Compatibility with other file types

### ISSUE THREAD

**Issue by nicooprat** [bancek/vscode-bem-expand#6]
Great idea, never thought of this use of the `&`. Would it be possible to make it work with other file types like `.php`, `.blade.php` (https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade), ...? Thanks!

**Comment by bancek** [comment]
It is possible to support them by adding this check:

https://github.com/bancek/vscode-bem-expand/blob/master/src/expand.ts#L49

You can add and test it and create a pull request.

**Comment by bancek** [comment]
Your pull request has been merged. Thank you for your contribution. I've released a new version. It should appear on the Marketplace soon.

**Comment by vega-wong** [comment]
#8 maybe you want to take a look for my sugguestion
